### ISSUE TITLE
Is there any way to let people register GitHub in China more easily?

### ISSUE THREAD

**Issue by randomwangran** [yangxcasdu/2019.md#1]
I don't have the condition now. But, I can help to find more robust way to do it.

- 手机自带的Safari浏览器，填入相同的信息，不一会儿，验证信息收到了，注册成功！
- 关掉电脑自带防火墙，又试了一次，成功，运气太好了！
- 使用 VPN 进行注册

(I will collect the method to solve this issue)

**Comment by yangxcasdu** [comment]
在[GitHub账户注册流程及常见问题解析](https://blog.csdn.net/weixin_42423311/article/details/84503654)这篇文章中提及。

- 使用VPN进行注册
