### ISSUE TITLE
re: 第四个问题之新手任务

### ISSUE THREAD

**Issue by randomwangran** [yangxcasdu/2019.md#2]
[第四个问题之新手任务](https://github.com/yangxcasdu/2019.md/blob/master/%E5%9C%A8Github%E9%81%87%E5%88%B0%E9%97%AE%E9%A2%98%E4%BB%A5%E5%8F%8A%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95.md#%E7%AC%AC%E5%9B%9B%E4%B8%AA%E9%97%AE%E9%A2%98%E4%B9%8B%E6%96%B0%E6%89%8B%E4%BB%BB%E5%8A%A1
):

现在觉得,本文是更好的新手任务.只要能做到编辑会刊,就算入门了.其他的方法,我们可以慢慢来学.

不如把这篇文字,放在 [introduction](https://github.com/casdu/introduction) 的首页位置?

**Comment by yangxcasdu** [comment]
那这样，我把新手任务这一部分，往后挪挪。

> 不如把这篇文字,放在 introduction 的首页位置?

可以啊~

**Comment by randomwangran** [comment]
想把你的权限提高到 member. 这样对 CASDU 里任何仓库都可以创作修改.

 @WokoLiu 似乎很忙最近,我试着联系他.

目前已经发送邀请了. https://github.com/casdu/introduction/invitations

**Comment by yangxcasdu** [comment]
收到，已更新
